<?php if($block->getData('id')): ?>
<?php endif; ?>
<?php if($block->getData('include_css') && $block->getData('include_css') == 'yes'): ?>
  <style>
    <?php echo $block->getData('id'); ?>
  </style>
<?php endif; ?>

<!-- /**  if($block->getData('include_name') && $block->getData('include_name') == 'yes'): ?>
   echo "1" ?>
 endif; ?> */ -->


<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

// $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeName       = $storeManager->getStore()->getName();
$storeName1       = $storeManager->getStore()->getCode();

// if ($block->getCustomerSession()->isLoggedIn()) {
//     $customerId = $block->getCustomerSession()->getCustomerId();
//     $customerId12 = $block->getCustomerSession()->getFirstname();
    


//     // echo $customerObj->getLastname();
//     $customerData = $block->getCustomerSession()->getCustomer();
//     // echo $customerId . '<br />';
   
//     // echo $block->getCustomerSession()->getCustomer()->getData();
// }
if ($customerSession->isLoggedIn()) {
    $customerId = $block->getCustomerSession()->getCustomerId();
    $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($customerId);

   
    // echo "aaa:".$block->getData('include_name');
    
   
     
    if($storeName == "Japanese" || $storeName1 =="ja_jp"  ) {
      echo "<div class='account-name'>";
      // echo "<span id='last-name-2'>"."Last name: ".$customerSession->getCustomer()->getLastname()."</span> <br>";
      // echo "<span id='first-name-2'>"."First name: ".$customerSession->getCustomer()->getFirstname()."</span>";
      if ($block->getData('include_name') == "1" )  {
         echo "ようこそ"." ".$customerObj->getFirstname()." ". $customerObj->getLastname()." さん";
      }
      else{
         echo "ようこそ"." ".$customerObj->getLastname()." ". $customerObj->getFirstname()." さん";
      }
      echo "</div>";
    }
    elseif($storeName == "English" || $storeName1 =="en_jp") {
      echo "<div class='account-name'>";
       if ($block->getData('include_name') == "6" )  {
         echo "Hello,"." ".$customerObj->getLastname()." ". $customerObj->getFirstname();
        }
        else{
           echo "Hello,"." ".$customerObj->getFirstname()." ". $customerObj->getLastname();
        }
      // echo "<span id='last-name-2'>"."Last name: ".$customerObj->getLastname()."</span> <br>";
      // echo "<span id='first-name-2'>"."First name: ".$customerObj->getFirstname()."</span>";
      echo "</div>";
    }
    elseif($storeName == "Chinese" || $storeName1 =="zh_jp") {
      echo "<div class='account-name'>";
      // echo "<span id='last-name-2'>"."Last name: ".$customerObj->getLastname()."</span> <br>";
      // echo "<span id='first-name-2'>"."First name: ".$customerObj->getFirstname()."</span>";
      if ($block->getData('include_name') == "3" )  {
         echo "你好!"." ".$customerObj->getFirstname()." ". $customerObj->getLastname();
      }
      else{
         echo "你好!"." ".$customerObj->getLastname()." ". $customerObj->getFirstname();
      }
     
      echo "</div>";
    }
    else{
      echo "<div class='account-name'>";
      // echo "<span id='last-name-2'>"."Last name: ".$customerObj->getLastname()."</span> <br>";
      // echo "<span id='first-name-2'>"."First name: ".$customerObj->getFirstname()."</span>";
      echo "Hello,"." ".$customerObj->getFirstname()." ". $customerObj->getLastname();
      echo "</div>";
    }
}
?>

